# Generated by Django 4.2 on 2023-04-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinstance',
            name='final_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='menuinstance',
            name='init_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
